### ISSUE TITLE
AppExtensions

### ISSUE THREAD

**Issue by realdadfish** [beworker/magnet#66]
The `AppExtension` from `magnetx-app` should pull in dependencies for application startup, even across (library) modules. So I followed the [example app's implementation closely](https://github.com/beworker/g1/blob/master/base/src/main/java/de/halfbit/g1/base/G1App.kt) and added in my `base` (actually `core`) module the said base application class. Then, in the main app module and a library module, I added two classes, similar to this:

```
@Instance(
    type = AppExtension::class,
    scoping = Scoping.UNSCOPED
)
internal class AppInitializer(private val application: Application) : AppExtension { ... }
```

and 

```
@Instance(
    type = AppExtension::class,
    scoping = Scoping.UNSCOPED
)
internal class FeatureInitializer(private val application: Application) : AppExtension { ... }
```

Now, I see that Magnet creates a Factory class annotated with `@FactoryIndex` (in package `magnet.index`) in both cases, but at runtime neither of both instances is injected into the `AppExtension.Delegate`. What am I doing wrong? How is this supposed to work?

**Comment by beworker** [comment]
Each magnet-apt enabled module generates factory and factory index classes. Factories are used at runtime to create DI instances. Factory index classes are pointers to the generated factories. They are only used at compile time to build "overall" factory index class called `MagnetIndex` and used at runtime.

Magnet needs an empty interface with `@Registry` annotation to be able to find all the factories via their factory index classes and to generate the `MagnetIndex` class. This interface (so called "assembly point") should be located in the main `app` module [like this one](https://github.com/beworker/g1/blob/master/app/src/main/java/de/halfbit/g1/Assembly.kt).

This is the only class to be stored in the `app` module. Besides keeping that interface, the main task of `app` module is to "assemble" other modules by adding dependencies to those in app's gradle file ([see this](https://github.com/beworker/g1/blob/master/app/build.gradle)). 

Thus a) make sure you have that "assembly point" interface in the `app` module and b) your app module has a dependency on `magnetx-app` extension and/or whatever else modules you have.

**Comment by realdadfish** [comment]
Ok, so `@Registry` (in our case still `@Magnetizier`) now lives in the `app` module and the first `AppExtension` living in the `app` module was found and injected. However, the second `AppExtension` found in a library module was not. The dependency is a transitive one, though, so

```
app <- library <- sub-library
```

All modules, `app`, `library` and `sub-library` have Magnet's `kapt` processor applied. The custom `AppExtension` lives in `sub-library`, only `library` is however referenced in `app`. Might this be the problem?

**Comment by beworker** [comment]
The issue is in the direction of dependencies. Because `app` module has no dependency on `sub-library`, it cannot find factories generated there. 

Magnet is built to support dependency inversion by design. This enforces some requirements on how the app should be structured. Proposed setup is to allow `app` have dependencies to any library modules and disallow library modules to have dependencies to the `app` module. It is described in [demo app](https://github.com/beworker/g1#structure) and in a [separate article](https://github.com/beworker/magnet/wiki/Dependency-inversion) explaining dependency inversion principle.

The ideal setup in your case should be like
```
app -> sub-library -> library
```
You can read is as  `app` assembles `sub-library` feature, which depends on `library`, into the build. There can be many of those "feature" modules that you can include or exclude from the final assembly. If you keep applying open/close and dependency inversion principles (remember that SOLID thing ;) though out your code, you will be able to add/remove features though gradle build file modification without any code adjustments.

If moving the code out of `app` module is too much work for you, you could try to move `@Magnetizier` into a separate module and let this modules "assemble" other modules instead of the `app` module. If you do so, you will most likely have to extract some stuff out of the app module into new modules to avoid circular dependencies. This will improve modularity though.

**Comment by realdadfish** [comment]
Hrm... I possibly draw the arrows in the wrong direction :) So, neither my `library` nor my `sub-library` have dependencies on the `app` module, they only depend on a `core` module, so it is probably more correct to write it as this:

```
app -> library -> sub-library -> core
// and btw. also
library -> sub-library2 -> core
library -> sub-library3 -> core
```

In `core` is an interface `A` that `sub-library` uses and `library` aggregates on (i.e. there is a class `B` that expects a `List<A>`, where each `A` comes from a different sub-library). In `app` I don't want to use `sub-library`, `sub-library2` or `sub-library3` directly, but aggregated through `library`. I understand now that I nonetheless have to add a direct dependency to these sub-libraries into `app` to make the injection work. Is this correct?

**Comment by beworker** [comment]
One way or another, the factories must be available on the `app's` classpath. You can either add a dependency directly from `app` to what you want to assemble, or use `api ` dependency between the modules to propagate their classes to the `library` and then only assemble the `library`. After trying out different options I prefer to use `api` dependency in conjunction with `internal` classes.

Having multiple `library` -> `sub-library` chains is perfectly fine. One side note though. There is a typical pattern and a typical class design I observed while being working with magnet. If there is an interface `A` which is implemented by multiple `A1`, `A2`,`A3` etc. classes and this interface is used by a single "aggregating" implementation `MasterA` as a List<A> then my preferred pattern looks like following.

I define `A-module` with `public interface A`  and `internal class MasterA` in it and then multiple `a1`, `a2`, `a3` etc. modules extend (have `api` dependency on) the `A-module`. The `app` then assemble some (or all, depending on the product configuration) of `a1`, `a2`, `a3` modules . I avoid putting my `A` interface into the  `core` module because `A` is a part of a feature (`A` + `MasterA` + `A1` or/and `A` + `MasterA` + `A2`) and I want to keep feature related code together. My consideration is that `A-module` defines an abstract feature, which can be extended/implemented by other modules. If I remove all implementation modules from the assembly, there is no reason for keeping `A` and `MasterA` in the build, which would be the case, if we put `A` into common `core`.

Maybe this could be somehow helpful to you too.

**Comment by realdadfish** [comment]
Many thanks for the help, this is much appreciated!
