### ISSUE TITLE
ViewModel injection

### ISSUE THREAD

**Issue by realdadfish** [beworker/magnet#69]
So, imagine I want to inject a `ViewModel` and would want to follow the (Dagger) approach outlined here: https://proandroiddev.com/viewmodel-with-dagger2-architecture-components-2e06f06c9455

This is the factory I need to use to provide instances (in `androidx.lifecycle.ViewModelProvider`):

```
public interface Factory {
    @NonNull
    <T extends ViewModel> T create(@NonNull Class<T> modelClass);
}
```

What would be my options in Magnet? As far as I know there is no Map-Injection. Injecting a `List<ViewModel>` would be possible, but this would mean _all_ `ViewModel`s would have to be instantiated before I could check which is the right one. If I would somehow `lazy` evaluate the thing by injecting a `List<Provider<ViewModel>>` (don't know if this is even possible), I have the issue that at runtime the actual type the provider provides is erased, so I wouldn't be able to pick the right one.

Now obviously I could create a separate factory instance for all my ViewModels, but this looks awkward:

```
val scope = getScope()
val viewModel = ViewModelProviders.of(this).get(MyViewModel::class.java) { modelClass ->
      MyViewModel(scope.getSingle<FirstDep>(), scope.getSingle<SecondDep>(), ...)
}
```

**Comment by beworker** [comment]
This can be achieved via a custom factory. Here is the factory I use for injecting `ViewModels` in my projects. I wanted to publish it as a magnet extension, but haven't succeeded yet.

```kotlin
const val VIEW_MODEL_KEY = "view-model-key"

class ViewModelFactory<T : ViewModel> : Factory<T> {

    override fun create(
        scope: Scope,
        type: Class<T>,
        classifier: String,
        scoping: Scoping,
        instantiator: Factory.Instantiator<T>
    ): T {
        val activity = scope.getSingle(FragmentActivity::class.java)
        val key = scope.getOptional(String::class.java, VIEW_MODEL_KEY)
        if (key != null && scoping != Scoping.UNSCOPED) {
            error("ViewModel '$type' with key '$key' must be declared with Scoping.UNSCOPED")
        }
        val provider = ViewModelProviders.of(activity, ActivityFactory(scope, instantiator))
        return if (key == null) provider.get(type) else provider.get(key, type)
    }

    private class ActivityFactory<T>(
        private var scope: Scope,
        private var instantiator: Factory.Instantiator<T>
    ) : ViewModelProvider.Factory {

        @Suppress("UNCHECKED_CAST")
        override fun <T : ViewModel?> create(modelClass: Class<T>): T =
            instantiator.instantiate(scope) as T
    }
}
```

It works as following. When you request a `ViewModel` from the scope, generated Magnet factory delegates that call to the custom factory above and the custom factory requests new or existing instance through Android `ViewModelProviders`. There are no needs for either Maps or Lists for keeping `ViewModels` instances because they are always requested right from where they are stored by the system.

Because of how instances are requested, the `ViewModel` should never be scoped and must have `Scoping.UNSCOPED` declaration on it. Here is how you apply the custom factory.

```kotlin
@Instance(
    type = PlayerViewModel::class,
    factory = ViewModelFactory::class,
    scoping = Scoping.UNSCOPED
)
class PlayerViewModel(
    playerUiOutlets: List<PlayerUi.Outlets>,
    playerUiControls: List<PlayerUi.Controls>
) : ViewModel() { }
```

Then in your client code you can inject this `ViewModel` via constructor parameters or using `getSingle()` function on a scope. The only requirement onto the scope (or its parent) is the requirement to provide `FragmentActivity`, because custom factory will use it for looking up the `ViewModel`.

```kotlin
private lateinit var viewModel: PlayerViewModel

override fun onCreate(savedInstanceState: Bundle?) {
        with(scope) {
            bind(this as FragmentActivity)
            viewModel = getSingle()
        }
        ...
}
```

Regarding the `VIEW_MODEL_KEY`, you can safely ignore it for now. It is intended for the case when you have multiple instances of a `ViewModel` of the same type, which can be parametrised with a `String` argument like ID or similar. Here is how I use it.

```kotlin
@Instance(
    type = OverviewViewModel::class,
    factory = ViewModelFactory::class,
    scoping = Scoping.UNSCOPED
)
internal class OverviewViewModel(
    @Classifier(VIEW_MODEL_KEY) private val assetId: String,
    private val overviewRepo: OverviewRepo<Item>
) : ViewModel() { }
```

```kotlin
private lateinit var viewModel: OverviewViewModel

override fun onCreate(savedInstanceState: Bundle?) {
        scope.apply {
            bind(assetId, VIEW_MODEL_KEY)
            viewModel = getSingle()
       }
}
```
In the configuration above `OverviewViewModel` will be instantiated multiple times once per `assetId` value, but will stay same for same `assetId`.

Hope this helps. As I mentioned already, once `ViewModelFactory` API is finalized I will publish it as a magnet extension. But it can be safely used also in its current state.

**Comment by realdadfish** [comment]
Ok, I used your code as base and allowed either fragment or activities to setup the `ViewModel`, like this:

```
class ViewModelFactory<T : ViewModel> : Factory<T> {
    override fun create(
        scope: Scope,
        type: Class<T>,
        classifier: String,
        scoping: Scoping,
        instantiator: Factory.Instantiator<T>
    ): T {
        val key = scope.getOptional(String::class.java, VIEW_MODEL_KEY)
        if (key != null && scoping != Scoping.UNSCOPED) {
            error("ViewModel '$type' with key '$key' must be declared with Scoping.UNSCOPED")
        }
        val androidViewModelFactory = AndroidViewModelFactory(scope, instantiator)
        val provider = getProviderFor(scope, androidViewModelFactory)
        return if (key == null) provider.get(type) else provider.get(key, type)
    }

    private fun getProviderFor(scope: Scope, viewModelProviderFactory: ViewModelProvider.Factory): ViewModelProvider {
        // fragment's have precedence over activities in the given scope
        val fragment = scope.getOptional(Fragment::class.java)
        if (fragment != null) {
            return ViewModelProviders.of(fragment, viewModelProviderFactory)
        }
        val activity = scope.getSingle(FragmentActivity::class.java)
        return ViewModelProviders.of(activity, viewModelProviderFactory)
    }

    private class AndroidViewModelFactory<T>(
        private var scope: Scope,
        private var instantiator: Factory.Instantiator<T>
    ) : ViewModelProvider.Factory {
        @Suppress("UNCHECKED_CAST")
        override fun <T : ViewModel?> create(modelClass: Class<T>): T =
            instantiator.instantiate(scope) as T
    }
}
```

But then I hit another road block - the `scope` lives as a member variable of the specific `Activity` or `Fragment` instance and is of course removed once the thing goes away. _However_, the `ViewModel` still holds references to instances _inside_ of the `scope`, since it is retained. Now if I have previously provided an `Activity` or `Fragment` instance to any of these instances inside the `ViewModel` I'm of course damned, as I'm effectively producing crashes and leaking the old `Activity` instance ultimatively bound to the Fragment in question.
So, to not fall into this trap I think one would actually need two different scopes - the one the `ViewModel` will live in, which will out-live the current `Fragment` / `Activity` instance and which will _not_ get a `Fragment` or an `Activity` provided, and optionally one scope that has these things, but is not used for `ViewModel` injection.

Ah, tricky stuff!

**Comment by beworker** [comment]
> _However_, the `ViewModel` still holds references to instances _inside_ of the `scope`, since it is retained.

You are right. This is because of the "broken" scoping of Android `ViewModel`. On one hand they are not allowed to have any dependencies on `Context` classes, besides maybe `Application` one, on the other hand they can only be created by providing such an activity scoped `Context`-class into `ViewModelProviders`. However if a `ViewModel` has no dependencies on `Context`-classes, everything works just fine.

Interestingly enough I went the same way you did. I had a version which could handle Fragments too, but it introduced more mess than it helped. I reverted back to Activity-only factory I published. Then I started thinking about adding some special build-time checks into compiler for dependencies to catch memory leaks, but they appeared to be very sophisticated and artificial. Then I started to think about adding another scope between Application and Activity one. I called it "retained" scope, but I've never had time to come back and implement it.

As of now I alway have leakcanary enabled in debug build and it let me know when I introduce prohibited dependency. Maybe you could approach this weakness and come up with some better/fresh ideas. It would be interesting to know how you handle it.

**Comment by realdadfish** [comment]
The problem with scopes (or components) for me is always that I want each of them to have a specific thing / place they're attached to, to ensure that if this thing goes away, the scope / component goes away as well. This is easy for application, activity and fragment, but for a "retained" scope this would mean the scope would have to live inside a retained fragment itself. And of course you'd naturally want to separate this "retained" thing from any other thing - in particular the actual viewmodel - even if it is tempting to just use that, since it is itself nothing more than a reference that is hold by an internal retained fragment.

Previously we did kind of a stupid thing - we had a Presenter that we wanted to retain, so we hacked together a `PresenterViewModel` that kept the `Presenter` alive for the time being. We wanted to get rid of that and go to full MVVM, but I think this could eventually be something to try and play around with, some kind of `ScopeViewModel` whose sole use is to hold the retained scope for an activity / fragment.

But then the usage of fragment / activity instances inside the viewmodel is still not properly possible, unless you create a redirect mechanism that would call back into the currently attached fragment / activity when needed, something like

```
@Instance(type = ActivityAware::class)
class ActivityAware {
    private var activity: Activity? = null
    fun withActivity(funn: Activity.() -> Unit) {
        activity?.let(funn)
    }
   internal fun setInstance(activity: Activity?) {
       this.activity = activity
   }
}
```

which would then be used like this:

```
class ScopeModel : ViewModel(), DefaultLifecycleObserver {
    private val scope by lazy { ... }
  
    override fun onCreate(owner: LifecycleOwner) {
        val aware = scope.getSingle(ActivityAware::class.java)
        if (owner is Activity) aware.setInstance(aware as Activity)
    }

    override fun onDestroy(owner: LifecycleOwner) {
        val aware = scope.getSingle(ActivityAware::class.java)
        aware.setInstance(null)
    }

    companion object {
        fun setup(activity: Fragment): ScopeModel {
            val viewModel = ViewModelProviders.of(fragment).get(ScopeModel::class.java)
            fragment.lifecycle.addObserver(viewModel)
            return viewModel
        }
    }
}
```

**Comment by realdadfish** [comment]
I got a compiling version: https://gist.github.com/realdadfish/4c65e2da781bebb1479bc4d4624c5fb7

Don't dare to try that out - task for tomorrow :)

**Comment by realdadfish** [comment]
Things seem to work out nicely, fixing up the tests. I'll close this issue for now and keep the Gist updated with a working version.

**Comment by beworker** [comment]
Hey @realdadfish!

I finally had some time to work on the magnetx extension for ViewModel. Here is the syntax I was thinking about.

```kotlin
class CatalogFragment : A3Fragment() {

    private val arg1: String = ...
    private val arg2: Int = ...

    private val viewModel by appScope
        .getViewModel<CatalogViewModel>(this) {
            bind(arg1)
            bind(arg2)
            ...
        }
}
```

* `appScope` is used as a base scope to prevent leakage of activity, fragment etc. to the ViewModel, when it gets created.
* `Scope.getViewModel()` is an extension function returning lazy view model instance.
  * The first parameter is an Android retention scope (either a `fragment` or an `activity`). It's given as a parameter and is not bound into the scope to prevent its leakage to the ViewModel.
  * The second parameter is an optional callback used for initializing the ViewModelScope instance which is, in turn, provided to the callback as the receiver. Parameters bound into this scope will be available to the ViewModel constructor.
  * ViewModelScope is a direct child of `appScope`. It can be cashed in fragment/activity and reused for creating other view models, if needed.
* Example `CatalogViewModel` can be either a pure interface (magic, magic - I will wrap it with a default ViewModel wrapper implementation when registering at Android API) or it can extend Android's `abstract class ViewModel` directly.

If you used it, would there be anything else what you would miss from this concept?

**Comment by beworker** [comment]
After trying out more options, this one has shown some disadvantages. Please ignore the question and sorry for the noice.

**Comment by realdadfish** [comment]
No problem, I'm happy with my current implementation :)
