### ISSUE TITLE
Using @Instance with Interface

### ISSUE THREAD

**Issue by Remicek** [beworker/magnet#70]

**Comment by Remicek** [comment]
Hello,
so I get an error when annotation interface with @Instance, that would make sense, but I am using factory param to delegate creation of this instance.

DataSource:13: error: Classes annotated with interface magnet.Instance must have exactly one public or package-protected constructor.

```
@Instance(
    type = DataSource::class,
    factory = DataSourceFactory::class
)
internal interface DataSource {
```

```
internal object DataSourceFactory : Factory<FitbitDataSource> {
    override fun create(
        scope: Scope,
        type: Class<DataSource>,
        classifier: String,
        scoping: Scoping,
        instantiator: Factory.Instantiator<DataSource>
    ): FitbitDataSource {
        val context = scope.getSingle(Context::class.java)
        val dependencyOne = scope.getSingle(dependencyOne::class.java)

        return DataSource(
            context,
           dependencyOne
        )
    }
}
```

**Comment by beworker** [comment]
`@Instance` can only be applied to a class, because even if you use a custom factory, you will still be given an `instantiator: Factory.Instantiator<DataSource>` which fallbacks to the generated factory, which, in turn, must be capable of creating an instance of a class. It would not be possible with an interface.

But you can apply `@Instance` to a function. If you make sure your custom factory never calls given `instantiator` instance, then it should work the way you want it to.

```kotlin
@Instance(
    type = DataSource::class,
    factory = DataSourceFactory::class
)
fun createDataSource(): DataSource {
    error("This method must never be called. Make sure to never call 'instantiator'.")
}
```
